# Generated by Django 4.0.2 on 2022-02-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='教師名稱')),
                ('gender', models.CharField(choices=[('0', '女'), ('1', '男'), ('2', '保密')], default='2', max_length=2, verbose_name='性別')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='教師姓名')),
                ('gender', models.CharField(choices=[('0', '女'), ('1', '男'), ('2', '保密')], default='2', max_length=2, verbose_name='性別')),
                ('photo', models.ImageField(upload_to='school/teachers/photo/', verbose_name='相片')),
                ('employment', models.DateField(auto_now_add=True, verbose_name='加入日期')),
                ('salary', models.DecimalField(decimal_places=0, default=100000, max_digits=8, verbose_name='薪資')),
                ('information', models.CharField(blank=True, max_length=512, null=True, verbose_name='教師介紹')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='課程名稱')),
                ('fee', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='學費')),
                ('start', models.DateField(verbose_name='開始日期')),
                ('end', models.DateField(verbose_name='結束日期')),
                ('limit', models.PositiveSmallIntegerField(verbose_name='人數上限')),
                ('comment', models.CharField(blank=True, max_length=512, null=True, verbose_name='課程說明')),
                ('status', models.BooleanField(default=True, verbose_name='開課狀態')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.teachers', verbose_name='授課教師')),
            ],
        ),
    ]
