# Generated by Django 4.0.3 on 2022-03-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_students_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': '課程資料', 'verbose_name_plural': '課程資料'},
        ),
        migrations.AddField(
            model_name='students',
            name='gold',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='儲值金'),
        ),
        migrations.AddField(
            model_name='students',
            name='information',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='學生介紹'),
        ),
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='school/student/photo/', verbose_name='相片'),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='school.courses', verbose_name='參與課程'),
        ),
    ]
