# Generated by Django 4.0.2 on 2022-02-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='上傳者')),
                ('file', models.FileField(blank=True, null=True, upload_to='reference/upload/file/', verbose_name='檔案')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reference/upload/image/', verbose_name='圖片')),
            ],
        ),
    ]
